### ISSUE TITLE
TransBTS2

### ISSUE THREAD

**Issue by NadiyaC249** [111Kaushal/Testing-and-validation-of-TransBTSV2#1]
hi it is really a good work！ thank you！ but  i cannot reproduce that  model i don't know why，should i change  something or not ？ can you upload your  test code for reference，expecting your  reply！ thx

**Comment by 111Kaushal** [comment]
Hello!
You need to download the original repository from here:- https://github.com/Wenxuan-1119/TransBTS and extract on your google drive. Then you can run the second line from the colab file we have uploaded as shown below.
 
!python  /content/drive/MyDrive/TransBTS-main/test.py --snapshot=False --post_process=False --load_file '/content/drive/MyDrive/TransBTS-main/checkpoint/TransBTS2022-03-29/model_epoch_935.pth' --num_workers=2 --output_dir='/content/drive/MyDrive/' --valid_dir '/content/drive/MyDrive/MICCAI_BraTS2020_ValidationData' --valid_file '/content/drive/MyDrive/TransBTS-main/valid.txt'

Make sure to change all the directories accordingly. The codes that we have uploaded are only snaps that work in conjunction with the main repository since we had to submit this project to professor in this format. Additionally on the main website of this repository all the steps to run the code have been mentioned in detail in the readme.pdf. Please do check it out. And we had to also apply a compression algorithm to make it work on colab since the dataset files are too big. Hence we first compressed all the downloaded dataset, uploaded it to google drive and then decompressed it on the fly during training/testing. The decompression steps have been shown in the training video , the link to which you can find on the main webpage of this repository.

If you have any further questions feel free to reach out.
